### PR TITLE
(Chaos) Updated for Data Correctness

### PR DESCRIPTION
**Pull request by tiltos**
- Beasts of Chaos updated

### CODE REVIEW

**Comment by tiltos** [comment]
Checked Allies, thralls and monsters. all clear there

**Comment by tiltos** [comment]
@krisling049 I've added a missing fighter here, but have never used Python. I've given it a dummy _id of `XXXXXX`. Can you please assign it a proper one?

**Comment by krisling049** [comment]
> @krisling049 I've added a missing fighter here, but have never used Python. I've given it a dummy _id of `XXXXXX`. Can you please assign it a proper one?

ID added :)

**Comment by tiltos** [comment]
@krisling049 one more new fighter ID needed mate, again listed under `XXXXXX`

**Pull request merged**
